import { useState } from 'react';
import { Box, Button, Card, CardContent, Grid, Stack, Typography } from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import { tokenStore } from '../api/client';
import { PageHeader } from '../components/shared';

const FORMATS: { fmt: string; label: string; desc: string }[] = [
  { fmt: 'csv', label: 'CSV Export', desc: 'Comma-separated values for spreadsheets.' },
  { fmt: 'excel', label: 'Excel Export', desc: 'Native .xlsx workbook.' },
  { fmt: 'pdf', label: 'PDF Export', desc: 'Formatted PDF report.' },
];

export default function Reports() {
  const [busy, setBusy] = useState('');

  // Authenticated file download via fetch + blob (Authorization header required).
  const download = async (fmt: string) => {
    setBusy(fmt);
    try {
      const resp = await fetch(`/api/v1/reports/export?fmt=${fmt}`, {
        headers: { Authorization: `Bearer ${tokenStore.access}` },
      });
      const blob = await resp.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      const ext = fmt === 'excel' ? 'xlsx' : fmt;
      a.href = url; a.download = `campaign_report.${ext}`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setBusy('');
    }
  };

  return (
    <Box>
      <PageHeader title="Reports" subtitle="Export campaign performance reports" />
      <Grid container spacing={2}>
        {FORMATS.map((f) => (
          <Grid item xs={12} sm={4} key={f.fmt}>
            <Card sx={{ height: '100%' }}>
              <CardContent>
                <Stack spacing={2}>
                  <Typography variant="h6">{f.label}</Typography>
                  <Typography variant="body2" color="text.secondary">{f.desc}</Typography>
                  <Button variant="contained" startIcon={<DownloadIcon />} disabled={busy === f.fmt}
                    onClick={() => download(f.fmt)}>
                    {busy === f.fmt ? 'Generating…' : 'Download'}
                  </Button>
                </Stack>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 3 }}>
        Scheduled reports (daily / weekly / monthly) can be defined via the API
        (<code>POST /api/v1/reports</code>) and are generated by the background scheduler.
      </Typography>
    </Box>
  );
}
